name: Tests

on: [ push ]

jobs:

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.113'
          
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - run: ./build.sh build -s true
        name: Build
        
      - run: ./build.sh test -s true
        name: Unit Tests

      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          
      - name: Docker compose launch
        run: |
          docker-compose -f tests-integration/docker-compose.yml up -d
      
      - run: ./build.sh integrate -s true
        name: Integration Tests

      - name: Test Results
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'build/output/junit-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_failure: true
          require_tests: true
          check_name: Test Results
