name: Tests

on: [ push ]

jobs:

  tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:

      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        if: ${{ !github.event.pull_request.head.repo.fork }}
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Docker compose launch
        run: |
          docker-compose -f ../tests-integration/docker-compose.yml up -d
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal